# Generated by Django 3.2.6 on 2021-08-24 20:41

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('website', models.URLField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('catch_phrase', models.CharField(max_length=128)),
                ('bs', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='main_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('suite', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('zipcode', models.CharField(max_length=128)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='main_app.user')),
            ],
        ),
    ]
